In [1]:
import numpy as np
import pandas as pd

# Baseline Recommender - Top N recommendations
This notebook is used to explore a top $N$ recommender as the baseline recommender, simply recommending the $N$ most bought items in the train data. A choice for $N$ could be $N=6$, since 6 items are displayed at a time in a row on the [Instacart website](https://www.instacart.com/store/walmart/storefront).

In [2]:
# load train data (prior)
df = pd.read_csv("data/order_products__prior.csv")

# grouping by product_id and counting the occurrence of each product across all orders
grouped_df = df.groupby(["product_id"])["product_id"].size().reset_index(name="product_id_count")

# sorting by count in descending order
sorted_df = grouped_df.sort_values("product_id_count", ascending=False)
print(sorted_df)

       product_id  product_id_count
24848       24852            472565
13172       13176            379450
21133       21137            264683
21899       21903            241921
47198       47209            213584
...           ...               ...
45884       45893                 1
13393       13397                 1
30445       30451                 1
42456       42464                 1
25244       25248                 1

[49677 rows x 2 columns]

In [3]:
# retrieving the top_n most bough products
top_n = 6
top_n_products = sorted_df.iloc[:6, :]["product_id"]
print(top_n_products)

24848    24852
13172    13176
21133    21137
21899    21903
47198    47209
47755    47766
Name: product_id, dtype: int64

In [4]:
orders_df = pd.read_csv("data/orders.csv")
orders_df

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0
...,...,...,...,...,...,...,...
3421078,2266710,206209,prior,10,5,18,29.0
3421079,1854736,206209,prior,11,4,10,30.0
3421080,626363,206209,prior,12,1,12,18.0
3421081,2977660,206209,prior,13,1,12,7.0
3421082,272231,206209,train,14,6,14,30.0

In [5]:
val_df = orders_df[orders_df["eval_set"] == "train"]   # contains only unique user_ids
val_df

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
10,1187899,1,train,11,4,8,14.0
25,1492625,2,train,15,1,11,30.0
49,2196797,5,train,5,0,11,6.0
74,525192,7,train,21,2,11,6.0
78,880375,8,train,4,1,14,10.0
...,...,...,...,...,...,...,...
3420838,2585586,206199,train,20,2,16,30.0
3420862,943915,206200,train,24,6,19,6.0
3420924,2371631,206203,train,6,4,19,30.0
3420933,1716008,206205,train,4,1,16,10.0
3421082,272231,206209,train,14,6,14,30.0

In [6]:
test_df = orders_df[orders_df["eval_set"] == "test"]   # contains only unique user_ids
test_df

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
38,2774568,3,test,13,5,15,11.0
44,329954,4,test,6,3,12,30.0
53,1528013,6,test,4,3,16,22.0
96,1376945,11,test,8,6,11,8.0
102,1356845,12,test,6,1,20,30.0
...,...,...,...,...,...,...,...
3420918,2728930,206202,test,23,2,17,6.0
3420929,350108,206204,test,5,4,14,14.0
3421001,1043943,206206,test,68,0,20,0.0
3421018,2821651,206207,test,17,2,13,14.0
3421068,803273,206208,test,50,5,11,4.0

In [7]:
order_products_train_df = pd.read_csv("data/order_products__train.csv")
order_products_train_df

         order_id  product_id  add_to_cart_order  reordered
0               1       49302                  1          1
1               1       11109                  2          1
2               1       10246                  3          0
3               1       49683                  4          0
4               1       43633                  5          1
...           ...         ...                ...        ...
1384612   3421063       14233                  3          1
1384613   3421063       35548                  4          1
1384614   3421070       35951                  1          1
1384615   3421070       16953                  2          1
1384616   3421070        4724                  3          1

[1384617 rows x 4 columns]

In [11]:
val_products_df = order_products_train_df.merge(val_df, on="order_id", how="left")[["product_id", "user_id"]]

In [14]:
val_products_df[val_products_df["user_id"] == 2]

        product_id  user_id
606747       22963        2
606748        7963        2
606749       16589        2
606750       32792        2
606751       41787        2
606752       22825        2
606753       13640        2
606754       24852        2
606755       45066        2
606756        9387        2
606757        5450        2
606758       24838        2
606759       38547        2
606760       19019        2
606761       12007        2
606762       26352        2
606763       22559        2
606764       45613        2
606765       31883        2
606766       12324        2
606767       33957        2
606768        5699        2
606769       31612        2
606770       34284        2
606771       48523        2
606772        2361        2
606773       48821        2
606774       11913        2
606775       45645        2
606776        1757        2
606777       21329        2

In [12]:
user_product_dict = val_products_df.groupby("user_id")["product_id"].apply(list).to_dict()
user_product_dict

{1: [196,
  25133,
  38928,
  26405,
  39657,
  10258,
  13032,
  26088,
  27845,
  49235,
  46149],
 2: [22963,
  7963,
  16589,
  32792,
  41787,
  22825,
  13640,
  24852,
  45066,
  9387,
  5450,
  24838,
  38547,
  19019,
  12007,
  26352,
  22559,
  45613,
  31883,
  12324,
  33957,
  5699,
  31612,
  34284,
  48523,
  2361,
  48821,
  11913,
  45645,
  1757,
  21329],
 5: [15349, 19057, 16185, 21413, 20843, 20114, 48204, 40706, 21616],
 7: [12053, 47272, 37999, 13198, 43967, 40852, 17638, 29894, 45066],
 8: [15937,
  5539,
  10960,
  23165,
  22247,
  4853,
  27104,
  7058,
  41259,
  37803,
  48230,
  47766,
  31717,
  21903,
  25659,
  41540,
  48121,
  2846],
 9: [27555,
  42347,
  27596,
  8834,
  26604,
  12075,
  8467,
  38988,
  30252,
  18926,
  24954,
  40571,
  1559,
  33754,
  29594,
  17600,
  42828,
  10132,
  20899,
  27973,
  41844,
  30967],
 10: [29650, 48720, 24654, 10177],
 13: [27435, 27086, 4210, 47078, 19934],
 14: [11042,
  32115,
  28601,
  29615,
  15869,
  37434,
  3808,
  15172,
  8744,
  29509,
  42284],
 17: [18534, 1217, 12720, 16797, 43352, 4374],
 18: [36216,
  47546,
  21137,
  5450,
  8518,
  22031,
  22888,
  11022,
  41463,
  25997,
  17461],
 21: [25740, 12683, 44632, 10957, 32645, 16615],
 23: [13544,
  42372,
  33819,
  33797,
  20468,
  13481,
  8224,
  14536,
  22021,
  49306,
  32327,
  48205],
 24: [31222],
 27: [2966,
  21386,
  11777,
  21137,
  4920,
  46906,
  33754,
  33787,
  46676,
  45446,
  32263,
  1323,
  44932,
  17553,
  10768,
  12745,
  37947],
 29: [39170,
  20305,
  6128,
  19541,
  35385,
  48800,
  39803,
  33945,
  1330,
  49615,
  31608,
  36543,
  37645,
  20874,
  42258,
  29267,
  35507],
 30: [23288],
 34: [27845, 24852, 38273, 7054, 27086],
 37: [21616,
  41665,
  5134,
  26790,
  43014,
  12204,
  26369,
  2243,
  4189,
  6607,
  45007,
  41065],
 38: [27231,
  9366,
  27086,
  4799,
  2086,
  27509,
  18337,
  4781,
  21198,
  15842,
  47209,
  36550,
  3397,
  12442,
  31343,
  26126,
  41950,
  19678,
  48205],
 41: [25890,
  15290,
  4605,
  24964,
  43961,
  18727,
  248,
  29180,
  28985,
  24184,
  27156,
  20520,
  18696,
  3661,
  47144],
 42: [28198, 13187, 22795, 39275, 9290, 8866, 30353],
 43: [24852,
  16797,
  1330,
  35079,
  29429,
  23909,
  3856,
  3990,
  36144,
  41602,
  2556,
  27796,
  46480,
  34940,
  42428,
  47014,
  11777,
  9076,
  19691,
  4920,
  29223,
  45066,
  8204,
  38154,
  22524,
  41302,
  48205,
  33027,
  15599,
  46981,
  42431,
  33780,
  9360],
 44: [49481, 48833, 43886, 9225, 35124, 35852],
 46: [24852, 42987, 24097, 4605, 21781, 13733],
 47: [33796, 16594, 29181, 8224, 30696, 43504],
 48: [22993,
  38277,
  45007,
  36695,
  44636,
  36389,
  34358,
  41238,
  34209,
  4855,
  41229,
  25890,
  29941],
 49: [36591, 7644, 18441, 18118, 27199, 34329],
 50: [6182, 47209, 13176, 16249, 21903, 31720],
 52: [46149,
  3798,
  24135,
  16797,
  43352,
  14032,
  39275,
  8048,
  30450,
  27839,
  30720],
 53: [16714,
  17659,
  11210,
  377,
  39124,
  1319,
  10339,
  4952,
  48453,
  17530,
  3390,
  29,
  35233],
 55: [7736,
  47766,
  4658,
  7413,
  39491,
  18175,
  46906,
  39349,
  48183,
  48890,
  27509,
  2389,
  12481],
 56: [24852, 25513, 21903, 31915, 13565, 32864, 47626, 26604, 25890],
 59: [13176,
  4472,
  40545,
  21137,
  47209,
  47888,
  10082,
  19611,
  44408,
  34949,
  27086,
  2825,
  23516,
  49533,
  34134,
  38223,
  22912,
  16479,
  42736,
  25931,
  10831],
 62: [37947,
  39121,
  8518,
  38288,
  49075,
  27012,
  27958,
  47626,
  7948,
  10246,
  39877,
  36695,
  40723,
  8277,
  36961,
  24852],
 63: [29820,
  11520,
  47672,
  1463,
  35383,
  13176,
  17758,
  49628,
  21137,
  6348,
  6719,
  24009,
  25659,
  2228],
 64: [13176,
  47209,
  46969,
  30391,
  40723,
  44359,
  18811,
  36550,
  8022,
  14947,
  5161,
  21903,
  4614,
  32303,
  45374,
  35004],
 65: [5161, 6656, 4920, 33768, 40604, 38164, 41561, 11534],
 66: [34503, 31103, 40256, 15872, 28842, 42014, 8143],
 67: [196, 6184, 13176],
 70: [24852],
 71: [117,
  48857,
  38689,
  22849,
  9598,
  14874,
  33754,
  21555,
  33529,
  48953,
  24964,
  7128,
  33290,
  20309,
  42075,
  3376,
  37973,
  15085,
  41860,
  47547,
  42356,
  12962,
  9385,
  26634,
  18367],
 72: [38689, 22281],
 74: [49111, 6740, 13629, 18479, 29898],
 76: [36107, 17858, 36545],
 78: [40648, 47759, 29127],
 79: [27845, 13176, 19057, 21137, 44910, 32747, 34243, 16616, 23233, 36550],
 80: [15842,
  8710,
  47630,
  13176,
  24010,
  33002,
  4792,
  12545,
  43713,
  48878,
  3583],
 81: [17313, 14159, 8048],
 82: [49235, 13176, 39581, 3798, 37710, 11759, 13591],
 83: [2186, 16254, 26856],
 84: [36127,
  47766,
  31717,
  46260,
  8518,
  23854,
  46526,
  481,
  9839,
  13176,
  18288,
  40709],
 86: [16349,
  45007,
  5876,
  5825,
  43789,
  16249,
  22935,
  35510,
  9092,
  890,
  49383,
  10565,
  27966,
  2228,
  13176,
  31915,
  8174],
 87: [3835, 30233, 29615, 24852, 19057, 3999, 15109],
 88: [35384, 31513, 49235],
 89: [35951,
  44815,
  23094,
  39558,
  42585,
  44359,
  16145,
  37147,
  24964,
  16759,
  15984,
  38312,
  19240,
  11250],
 90: [33318, 32648, 36994, 19204, 939],
 91: [5876,
  47209,
  17835,
  1463,
  8467,
  34668,
  30169,
  9515,
  33754,
  42536,
  27750,
  651,
  11005,
  5449,
  27156,
  5134,
  19816,
  9364,
  20520,
  5337,
  21903,
  49235,
  45535,
  16759,
  37637,
  7500,
  22559,
  48628,
  29987,
  22035,
  17949,
  21938,
  41570,
  24852],
 93: [16812, 1295, 44477, 6898, 40858, 38777, 28836, 41290],
 95: [24838,
  47156,
  45368,
  20754,
  48554,
  22935,
  32734,
  26209,
  47626,
  5134,
  18889,
  33731,
  21278,
  16083,
  41544,
  47065,
  38249,
  4410],
 96: [31371,
  43304,
  32578,
  27966,
  39275,
  2228,
  26298,
  20995,
  3142,
  8672,
  11352],
 97: [23224],
 99: [13176,
  21903,
  23029,
  42342,
  22035,
  31717,
  15290,
  36522,
  45073,
  4605,
  21137,
  26497,
  43961,
  27024,
  42719],
 102: [28842,
  28985,
  14870,
  36735,
  30720,
  21903,
  47626,
  43352,
  21183,
  21174,
  48885,
  14898,
  44359,
  46979,
  33438,
  13535,
  23645],
 103: [13225],
 104: [40052,
  5456,
  36735,
  49131,
  27344,
  41521,
  15728,
  4294,
  19425,
  2335,
  6778],
 105: [12341, 26317, 27323, 25878],
 106: [6813,
  35534,
  37089,
  17335,
  16797,
  43352,
  26604,
  25272,
  24852,
  29657,
  14320,
  47941,
  39066,
  40287,
  20561,
  46842,
  28646],
 108: [44359, 42736, 28278, 31343, 47209, 19057, 22935, 10749, 17721],
 109: [36273,
  26477,
  46266,
  33909,
  47144,
  16185,
  5450,
  20378,
  30406,
  21936,
  35042,
  6473,
  5618,
  41591,
  36753,
  34494,
  13976],
 110: [24852,
  40310,
  42244,
  10749,
  21077,
  8424,
  30391,
  21137,
  41220,
  8518,
  33787,
  4957,
  260,
  26384,
  17948,
  44359,
  41149,
  4809,
  30489,
  47766,
  35951,
  43961],
 111: [25985,
  32655,
  7644,
  16797,
  39844,
  17151,
  32727,
  17487,
  27966,
  28204,
  49352,
  8073,
  27344,
  13176,
  5077,
  31618,
  41385,
  32994,
  28968,
  21195,
  2338,
  7175,
  10521,
  21938],
 112: [432],
 113: [15680, 5157],
 114: [17794,
  22935,
  19049,
  46667,
  45535,
  25890,
  3142,
  47626,
  25811,
  4352,
  38739,
  40706,
  30391,
  10749,
  2295,
  24680,
  21137,
  2067,
  1712,
  46229],
 115: [48127,
  35951,
  46720,
  18441,
  38730,
  6567,
  32653,
  14133,
  8518,
  48287,
  27695,
  29142,
  18615],
 116: [25464, 19488, 42677, 46673, 45055],
 117: [29503, 6427, 37465, 2097, 43879, 6716, 29659, 1512, 21306],
 118: [13176, 46676, 37646, 22825],
 119: [2855,
  6348,
  13380,
  25623,
  42265,
  35522,
  19019,
  41198,
  3255,
  4656,
  8277,
  18352,
  39747,
  17828,
  9339],
 120: [36472],
 121: [48364, 25931, 42244, 29941, 46906],
 123: [11759,
  25653,
  26914,
  30720,
  38768,
  12341,
  30731,
  35561,
  35951,
  25170,
  35336],
 124: [29223, 24184, 429, 45290, 19478, 26324, 19760, 11152, 47145],
 125: [18439,
  37543,
  29503,
  13287,
  10613,
  27356,
  20463,
  9755,
  47024,
  13866,
  34726,
  29176,
  16305,
  31876,
  7877,
  17318,
  38390,
  43056,
  39646],
 128: [25005, 11512, 40198, 30949, 43643, 43713, 18152, 43798, 48220, 15984],
 130: [47626, 24852, 27845, 35221, 27344, 8087, 46654, 12099, 1215],
 131: [13646, 15011, 42244, 33731, 28934, 41950, 16797, 43789],
 132: [24957, 9172, 34243, 27845, 42445, 27086],
 135: [21553,
  16234,
  14999,
  43961,
  25273,
  4347,
  16020,
  21137,
  38777,
  41787,
  37646,
  2078],
 138: [42475],
 139: [20940, 41400, 34005],
 140: [432,
  11777,
  27845,
  13176,
  34262,
  5973,
  11520,
  9070,
  14573,
  43713,
  12206,
  20810,
  31343,
  31130,
  1503,
  17872,
  48057,
  1000,
  24372,
  38618,
  19894,
  40849,
  18362],
 142: [28666, 32566, 48857, 4920, 34270, 23375],
 143: [40723,
  12384,
  18465,
  8153,
  2966,
  48226,
  37229,
  9862,
  1529,
  23375,
  6193,
  10995,
  26632,
  47865],
 144: [39527, 36735, 36746],
 145: [47591, 21267, 37947, 10768, 17553, 43616, 36735, 26604],
 146: [11361,
  8153,
  6383,
  9076,
  36695,
  21137,
  2513,
  5025,
  1541,
  34969,
  18598,
  36486,
  43704,
  32689,
  39009,
  48015,
  31506],
 147: [38164,
  21019,
  43961,
  2390,
  38656,
  18205,
  38548,
  25934,
  49026,
  40102,
  48370,
  13772,
  38374],
 148: [30391, 10983, 20632, 47209, 25339, 45747, 12576],
 150: [28058, 35518],
 155: [12384, 43154, 30630],
 157: [47280, 15399, 23554, 13176, 43394, 14867, 24236, 42579],
 160: [40022,
  40009,
  33589,
  14999,
  49007,
  13249,
  17951,
  32632,
  1170,
  1069,
  9551,
  10193,
  13829,
  21709,
  7925,
  54,
  15290,
  39993,
  48527,
  6789],
 161: [45504,
  2748,
  28699,
  21137,
  27966,
  35887,
  47209,
  9390,
  14976,
  31343,
  18272,
  41950,
  9595,
  2452,
  43504,
  29311,
  28842],
 163: [42327, 14036, 31803, 22721, 36214, 47766, 16610, 26981, 12391],
 164: [35121, 21903, 10212, 34969, 39721, 41140, 2086, 4942, 34905, 17620],
 167: [8237,
  42014,
  41674,
  40332,
  6318,
  10145,
  4,
  34619,
  26520,
  8920,
  17562,
  32947,
  21293,
  46513,
  44125,
  11265,
  34449,
  17484],
 169: [32689,
  6873,
  24184,
  9786,
  40334,
  49521,
  12703,
  3952,
  9405,
  21616,
  21903],
 171: [29640,
  9225,
  34534,
  47107,
  6793,
  41319,
  26246,
  44500,
  19604,
  24129,
  24852,
  20754,
  45368],
 173: [4920, 2361, 28038, 22511, 49191],
 174: [9047, 34688, 19513, 38274, 27695],
 175: [28199],
 176: [24852, 31958, 20995, 44632, 13639, 25985, 30305],
 178: [46346],
 179: [30169, 28985, 15872, 46667, 21334, 26604, 46979],
 183: [12894,
  6046,
  32293,
  46175,
  43389,
  22237,
  41782,
  35339,
  34,
  32347,
  4614,
  44272,
  18523,
  33754,
  4957,
  1447,
  20736,
  27344,
  24467,
  14645,
  39220,
  29487,
  40992,
  33994,
  31343,
  3800,
  43262],
 184: [41806,
  11576,
  23233,
  22220,
  31076,
  39557,
  41332,
  39276,
  12572,
  37382,
  42992,
  41179,
  5539,
  15981,
  14852,
  23375,
  49383,
  46139,
  39055,
  17835,
  5031,
  12941,
  16797,
  17104,
  45608,
  47977],
 185: [46605],
 187: [3957, 36484, 12324, 6284, 27377, 3398, 8274, 23148, 7328, 1160, 34778],
 189: [45504, 13176, 2748, 47766, 5479],
 191: [7673, 36082, 24838, 20512, 13176, 34940, 1139],
 192: [26317, 12078, 13176, 651, 35561, 13032, 40199, 21195],
 193: [44075, 40268, 41319, 45906, 30450, 21376, 18150],
 195: [31651, 32303, 19691, 3798, 500, 29015],
 197: [3918,
  35004,
  3397,
  30658,
  8174,
  36867,
  8955,
  9472,
  21903,
  35921,
  46979,
  47766,
  49383,
  39877,
  17794,
  17461,
  21910,
  27845,
  13409,
  48679,
  24964,
  43165,
  12033,
  8555,
  16797,
  39160,
  33754,
  40571,
  4957,
  11925,
  14917],
 198: [28849, 22760],
 199: [21903, 27521, 31717, 33757, 24583, 16521, 19660, 42265, 25659],
 201: [329, 9337, 43129],
 203: [17902],
 204: [42637,
  4472,
  48220,
  38312,
  7515,
  4350,
  7870,
  31772,
  26856,
  21137,
  39619,
  19478,
  32486,
  18465,
  260,
  31618,
  3464,
  26756,
  13829,
  41950,
  12703],
 205: [40910, 29662, 41658, 21775, 24086, 4605, 22035, 3376],
 206: [41716, 42585, 40396, 40961, 27817, 8518, 24964, 7485],
 208: [40396, 6873, 31717, 23803, 33120],
 209: [37418, 35942, 20876, 4297, 20413, 24852, 48335, 10840, 13012],
 210: [23909,
  8174,
  38739,
  41678,
  8277,
  32030,
  40198,
  46886,
  21903,
  21137,
  23375,
  4799,
  27715,
  49075,
  343,
  27156,
  23695,
  23734,
  34969,
  40233,
  49437,
  42585],
 211: [24852,
  40332,
  4605,
  31553,
  47626,
  44142,
  2966,
  11937,
  20378,
  21011,
  33184,
  30989,
  36290,
  13444,
  12087,
  32489,
  34523,
  43452,
  12939,
  11526,
  29487,
  21903,
  21288,
  9076,
  14897,
  38168,
  30391],
 212: [11712, 1979, 14715],
 213: [41148,
  24852,
  36550,
  10798,
  40974,
  26922,
  26124,
  13829,
  11576,
  35561,
  39993,
  44449,
  27683,
  28348,
  11755,
  22999,
  11461,
  13076,
  9159,
  14536,
  23734,
  33245,
  21511,
  17795,
  11678],
 214: [25659,
  47991,
  39928,
  16797,
  44814,
  3826,
  42768,
  48679,
  21903,
  8988,
  28350,
  19162,
  47209,
  16278,
  6292,
  5876,
  43922,
  44359,
  35853,
  11959,
  45801,
  9092,
  36180,
  10385,
  23919,
  27900,
  38182,
  46106,
  43961,
  47873,
  10351,
  25472,
  43740,
  16864,
  31779,
  47156],
 215: [42811,
  45211,
  12206,
  37654,
  31683,
  21386,
  33379,
  44014,
  10492,
  7189,
  34111,
  6441,
  47937,
  48246],
 217: [12745,
  10768,
  26915,
  37947,
  17553,
  10912,
  11499,
  27544,
  17461,
  16759,
  10246,
  42625,
  38383,
  18883,
  29941,
  19527,
  5451,
  23854,
  1025,
  5212,
  46654],
 218: [19116],
 219: [26094,
  37654,
  14861,
  25466,
  21288,
  1994,
  32650,
  30353,
  23047,
  34993,
  12576,
  35368,
  12782,
  12156,
  40486,
  3614,
  15869,
  32331,
  42372,
  15926,
  21701,
  1006,
  16614],
 220: [7781, 28476, 31343, 35887, 42445],
 222: [48015, 4210, 2707, 20320, 45531, 1775, 4313],
 223: [1426, 28054, 21903],
 224: [8193, 45036, 9839, 2846, 46575, 47042, 42736, 11078],
 226: [24852,
  29363,
  16485,
  31981,
  13029,
  15268,
  9076,
  4137,
  13423,
  39646,
  32399,
  25544,
  6340,
  7751],
 229: [34593, 33754, 40571, 4957, 33787, 14917, 42265, 6740, 36216, 9138],
 230: [20876,
  20039,
  18465,
  49185,
  23088,
  48866,
  48335,
  17160,
  3843,
  34466,
  20536,
  21938,
  26579,
  2295,
  10749,
  22935,
  8006],
 231: [8174,
  31720,
  43662,
  18362,
  43122,
  33055,
  49374,
  17974,
  5707,
  26427,
  22825,
  44636,
  2067,
  43086,
  6046,
  49235,
  21938,
  21405],
 235: [12916,
  26620,
  48523,
  24852,
  49270,
  9383,
  47194,
  39947,
  45066,
  22400,
  37158,
  25513,
  14048],
 238: [42394,
  12159,
  42360,
  6867,
  30549,
  18725,
  19097,
  35336,
  19348,
  10673,
  39174,
  13869,
  17896,
  2702,
  5994,
  3285,
  10365,
  6631,
  46595,
  54,
  5097,
  43556,
  27510,
  22463,
  17993,
  11827,
  31486,
  4216,
  25543,
  43461,
  30696,
  36689,
  47631,
  26360,
  8494,
  10990,
  21011,
  46520,
  24146,
  33772,
  13966,
  17322,
  31966,
  10695,
  44041,
  39735,
  26312,
  47966,
  47226,
  4635,
  46598,
  13767,
  18987,
  1950,
  13194,
  33464,
  30340],
 239: [29487,
  44449,
  41787,
  46802,
  21903,
  21709,
  17878,
  14364,
  21938,
  28842,
  5818],
 240: [38928, 38440],
 242: [18659, 4088, 9076, 26165, 10673],
 243: [27104,
  46979,
  45066,
  21137,
  45007,
  27086,
  24184,
  5450,
  47626,
  4562,
  43789,
  15937],
 245: [1463,
  38622,
  43154,
  23029,
  12703,
  1787,
  49235,
  7521,
  13176,
  26209,
  29418],
 249: [24852, 41220, 47766, 20822],
 250: [5785,
  14398,
  605,
  23233,
  42828,
  43504,
  26790,
  30233,
  13807,
  22035,
  12564,
  47884,
  33731],
 252: [4781,
  3880,
  17409,
  10049,
  3358,
  36144,
  10521,
  23687,
  32689,
  33117,
  7644,
  28993,
  14287,
  35551,
  27143,
  23388,
  35341,
  9411,
  17008,
  14124,
  37194],
 253: [10278, 30113, 46616],
 255: [42828, 38849, 4541, 25588, 11556, 19019, 10528],
 256: [432,
  48041,
  32842,
  12099,
  37742,
  3473,
  7349,
  45394,
  13828,
  16144,
  47790],
 258: [34, 8859, 20574, 11452, 8193],
 259: [32192, 31506, 44912, 45894],
 260: [19691, 32303, 43352, 35267],
 261: [8390,
  46735,
  30356,
  23665,
  25008,
  38314,
  43907,
  1806,
  32165,
  14432,
  12528,
  2530,
  3685,
  25049,
  37404,
  34808,
  39276,
  5025,
  48364,
  49381,
  26497,
  14124,
  33047,
  22948,
  40631,
  40214,
  36780,
  28270,
  5618,
  21692],
 262: [19348, 3407, 24239, 14772],
 264: [14197,
  40556,
  20114,
  44449,
  22504,
  41544,
  17949,
  42244,
  33787,
  38689,
  49235,
  5212,
  47766,
  24852,
  28842,
  38593,
  12576,
  35887,
  8412,
  14711,
  1158,
  24830,
  30489,
  8239],
 267: [17330,
  4595,
  48144,
  7644,
  10573,
  25952,
  27356,
  29503,
  15424,
  23909,
  32602,
  31564,
  16020,
  22989,
  22028],
 270: [28413, 3298, 30827, 10326, 21292, 19691, 16797],
 271: [11885],
 272: [939, 3696, 1405, 9755, 18667, 24915, 44487, 19006],
 273: [13176, 11233, 35458, 33791, 19057, 21137, 43352, 38558, 37067, 39275],
 278: [27086],
 280: [41844,
  27548,
  40174,
  13176,
  47766,
  21137,
  26790,
  40706,
  37646,
  22825,
  20082],
 282: [46175, 45681, 26634, 32580, 1039, 10725, 35649],
 283: [41596, 43352, 16797, 32303, 32971, 41973],
 284: [49235,
  35951,
  32579,
  30066,
  25659,
  35750,
  9366,
  43999,
  20878,
  24686,
  8277,
  5334,
  36322],
 285: [24852, 47344, 6459, 21137, 12409, 39216, 24253],
 286: [17261, 6679],
 288: [12492,
  46807,
  29557,
  39468,
  32647,
  43352,
  16797,
  9076,
  47630,
  20591,
  27845],
 289: [13176,
  47209,
  47042,
  35503,
  21137,
  16759,
  30442,
  22035,
  45374,
  42719,
  6187],
 291: [42282],
 293: [26911,
  47209,
  14084,
  21903,
  42265,
  13177,
  46370,
  27241,
  17948,
  25659,
  21436,
  14643,
  21841,
  48679,
  23081,
  22935,
  49267],
 294: [21334, 8197, 45007, 5876, 34126, 9403],
 295: [3957,
  34270,
  9623,
  8174,
  5212,
  30489,
  46802,
  21137,
  43768,
  28476,
  45066,
  17794,
  18048,
  5161],
 296: [4812,
  17622,
  46807,
  41658,
  37478,
  23622,
  7751,
  34061,
  5491,
  14491,
  16384,
  7084,
  1387],
 298: [29103,
  39046,
  10957,
  45687,
  33129,
  13375,
  7571,
  43961,
  44129,
  48069,
  22559,
  25676,
  3919,
  5098,
  44706,
  1516,
  4635,
  41377],
 300: [19272,
  44825,
  40427,
  47209,
  43858,
  4472,
  7251,
  35675,
  33443,
  18677,
  47652,
  44703,
  7381,
  1883,
  40645],
 304: [13870, 40691, 20339, 14371, 46681, 35688],
 305: [2078,
  45202,
  14947,
  17948,
  34590,
  42265,
  24973,
  6015,
  37646,
  47759,
  19208],
 306: [21137, 43352, 6615, 12341],
 309: [19678,
  4605,
  2380,
  37107,
  29487,
  8670,
  37046,
  46667,
  35209,
  18531,
  38650,
  49284,
  25659,
  28985],
 310: [45061, 28464, 12626, 4818],
 313: [22935, 41950, 44471, 18465, 30391, 42768],
 314: [1808],
 315: [21158,
  4920,
  25885,
  7877,
  26648,
  19003,
  4564,
  31553,
  38028,
  17859,
  16776,
  46454,
  27662],
 317: [33502, 25985, 25132],
 319: [43352, 42617, 19057, 9825, 33407, 24852, 13431, 11068, 48255],
 322: [9631, 10749, 15503, 920, 24964, 5876, 9550, 47209],
 323: [25133,
  30169,
  46676,
  30727,
  9550,
  15740,
  29752,
  25630,
  8516,
  35221,
  49533],
 324: [6631, 5782, 24852, 42796, 31461, 31766],
 325: [35183, 32360, 15912, 27104, 22935, 44359, 47209, 21616, 41593],
 326: [7249, 31651, 22507],
 327: [18382,
  9154,
  6475,
  23029,
  22963,
  33731,
  2468,
  13517,
  46584,
  2326,
  32665],
 328: [49193, 40174, 16953],
 329: [9337,
  38739,
  26315,
  13524,
  45371,
  41665,
  22206,
  41844,
  17518,
  38312,
  31727,
  16349,
  45615,
  49555,
  16847,
  5539,
  22627,
  7795,
  41551,
  33950,
  19691,
  16973,
  24964],
 330: [1194, 10500, 18524, 19303, 14871],
 334: [18441, 17830, 22035, 49086, 2043, 24097],
 337: [19348,
  27945,
  14870,
  44156,
  2639,
  23106,
  24390,
  44632,
  49191,
  29340,
  33129,
  13672,
  2784,
  9755,
  36170,
  7914,
  38739,
  39051,
  39190,
  41746,
  17634,
  42585,
  32465,
  25544,
  24680,